export const categories = [
  {
    id: 1,
    name: "Enduro",
    slug: "enduro",
    icon: "/images/categories/enduro.png",
  },
  {
    id: 4,
    name: "Motorcross",
    slug: "motorcross",
    icon: "/images/categories/motorcross.png",
  },
  {
    id: 2,
    name: "Adventure",
    slug: "adventure",
    icon: "/images/categories/adventure.png",
  },
  {
    id: 3,
    name: "Street",
    slug: "street",
    icon: "/images/categories/street.png",
  },
  {
    id: 5,
    name: "Sport",
    slug: "sport",
    icon: "/images/categories/sport.png",
  },
];

export const bikes = [
  {
    id: 1,
    category: "Enduro",
    name: "KTM 300 EXC",
    slug: "ktm-300-exc",
    tour: true,
    rental: true,
    buy: true,
    image: "ktm-exc-300.jpg",
    shout: "The ultimate offroad hard enduro machine",
    description:
      "The KTM 300 EXC maintains legendary status as the undisputed King of enduro. Not only does it have the most recognized title at the sharp end of hard enduro, it's still unmatched when it comes to 2-stroke ingenuity, fury, and downright fun. With a bulletproof, fuel-injected 2-stroke engine churning out masses of low-down torque and top-end fury, it's the ideal companion when tackling challenging terrain.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "electric",
    cooling: "liquid",
    gears: 6,
    horespower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durable",
      "nimble",
      "reliable",
      "comfortable",
      "lightweight",
      "versatile",
      "offroad",
      "pro racing",
    ],
  },
  {
    id: 2,
    category: "Adventure",
    name: "KTM 790 Adventure",
    slug: "ktm-790-adv",
    tour: false,
    rental: true,
    buy: true,
    image: "ktm-790-adv.jpg",
    shout: "The do it all adventure machine, both on and offroad",
    description:
      "The KTM 790 ADVENTURE is designed to make 2-wheeled adventure travel easier. Capable, comfortable, and cost-effective, it not only ticks all the boxes of what an adventure machine should be. instead, it breaks out of the box altogether. Built around a torquey parallel twin-cylinder powerplant, and boasting a class-leading electronics package, it's the perfect choice for riders looking to chase the horizon.",
    weight: 203,
    tank: 20,
    displacement: 293,
    cylinders: 2,
    stroke: 4,
    seatHeight: 860,
    starter: "electric",
    cooling: "liquid",
    gears: 6,
    horespower: 94,
    kw: 70,
    maxSpeed: 210,
    price: 13000,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durable",
      "reliable",
      "comfortable",
      "tourer",
      "long distance",
      "versatile",
      "offroad",
      "adventure",
      "street",
    ],
  },

  {
    id: 3,
    category: "Street",
    name: "KTM Duke 125",
    slug: "ktm-duke-125",
    tour: false,
    rental: true,
    buy: true,
    image: "duke.jpeg",
    shout: "The ultimate street bike",
    description:
      "The KTM Duke is known for being the apex predator in its domain, boasting the most powerful 125 engine on the market.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "electric",
    cooling: "liquid",
    gears: 6,
    horespower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durable",
      "nimble",
      "reliable",
      "comfortable",
      "lightweight",
      "versatile",
      "offroad",
      "pro racing",
    ],
  },
  {
    id: 4,
    category: "Adventure",
    name: "GAS GAS 700 ES",
    slug: "gasgas-700-es",
    tour: false,
    rental: true,
    buy: true,
    image: "gasgas-700-es.jpeg",
    shout: "The ultimate adventure machine",
    description:
      "Turning every road and offroad track into a series of ongoing playgrounds, the lively handling and offroad inspired centered riding position inspires confidence and inject fun into every ride.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "electric",
    cooling: "liquid",
    gears: 6,
    horespower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durable",
      "nimble",
      "reliable",
      "comfortable",
      "lightweight",
      "versatile",
      "offroad",
      "pro racing",
    ],
  },
];
