export const categories = [
  {
    id: 1,
    name: "Enduro",
    slug: "enduro",
    icon: "/images/categories/enduro.png",
  },
  {
    id: 4,
    name: "Motocross",
    slug: "motocross",
    icon: "/images/categories/motocross.png",
  },
  {
    id: 2,
    name: "Aventura",
    slug: "adventure",
    icon: "/images/categories/adventure.png",
  },
  {
    id: 3,
    name: "Street",
    slug: "street",
    icon: "/images/categories/street.png",
  },
  {
    id: 5,
    name: "Esporte",
    slug: "sport",
    icon: "/images/categories/sport.png",
  },
];

export const bikesEnduro = [
  {
    id: 1,
    category: "Enduro",
    name: "KTM 300 EXC",
    slug: "ktm-300-exc",
    specsTrue: true,

    tour: true,
    rental: true,
    buy: true,
    image: "ktm-exc-300.jpg",
    shout: "A máquina definitiva de enduro duro fora de estrada",
    description:
      "A KTM 300 EXC mantém o status lendário como o Rei indiscutível do enduro. Não só tem o título mais reconhecido no topo do enduro duro, como ainda é imbatível quando se trata de engenhosidade, fúria e diversão em 2 tempos. Com um motor 2 tempos injetado de combustível e indestrutível, que produz uma enorme quantidade de torque em baixa rotação e fúria na alta rotação, é o companheiro ideal ao enfrentar terrenos desafiadores.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },

  {
    id: 2,
    category: "Enduro",
    name: "GAS GAS 300 EC",
    specsTrue: true,
    slug: "gasgas-300-ec",
    tour: true,
    rental: true,
    buy: true,
    image: "gasgas-300-ec.jpeg",
    shout: "A máquina definitiva de enduro duro fora de estrada",
    description:
      "Prefere enduro técnico a desviar de árvores em alta velocidade? Bem, se o que te empolga é o extremo, então a nossa EC 300 é definitivamente para você! Projetada do zero para enfrentar o terreno mais áspero, esta máquina de enduro ultra-moderna é leve, poderosa e faz o trabalho facilmente. Com muito torque em baixa rotação e suspensão WP macia e fácil de ajustar, esses longos e cansativos dias na moto se tornam muito mais agradáveis a bordo da EC 300. Então, para onde você vai levar a sua?",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 10500,
    manufacturer: "GAS GAS",
    link: "https://www.gasgas.com/en-pt/models/enduro/2-stroke/ec-300-2025.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },
];

export const bikes_PT = [
  {
    id: 1,
    category: "Enduro",
    name: "KTM 300 EXC",
    slug: "ktm-300-exc",
    tour: true,
    rental: true,
    specsTrue: true,

    buy: true,
    image: "ktm-exc-300.jpg",
    shout: "A máquina definitiva de enduro duro fora de estrada",
    description:
      "A KTM 300 EXC mantém o status lendário como o Rei indiscutível do enduro. Não só tem o título mais reconhecido no topo do enduro duro, como ainda é imbatível quando se trata de engenhosidade, fúria e diversão em 2 tempos. Com um motor 2 tempos injetado de combustível e indestrutível, que produz uma enorme quantidade de torque em baixa rotação e fúria na alta rotação, é o companheiro ideal ao enfrentar terrenos desafiadores.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },
  {
    id: 2,
    category: "Aventura",
    name: "KTM 790 Adventure",
    specsTrue: false,

    slug: "ktm-790-adv",
    tour: false,
    rental: true,
    buy: true,
    image: "ktm-790-adv.jpg",
    shout:
      "A máquina de aventura que faz tudo, tanto na estrada quanto fora dela",
    description:
      "A KTM 790 ADVENTURE foi projetada para tornar as viagens de aventura sobre duas rodas mais fáceis. Capaz, confortável e econômica, não só atende a todos os requisitos do que uma máquina de aventura deve ser. Em vez disso, ela quebra todos os padrões. Construída em torno de um motor paralelo de cilindros duplos com muito torque, e ostentando um pacote eletrônico líder na classe, é a escolha perfeita para pilotos que procuram seguir o horizonte.",
    weight: 203,
    tank: 20,
    displacement: 293,
    cylinders: 2,
    stroke: 4,
    seatHeight: 860,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 94,
    kw: 70,
    maxSpeed: 210,
    price: 13000,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durável",
      "confiável",
      "confortável",
      "tourer",
      "longa distância",
      "versátil",
      "fora de estrada",
      "aventura",
      "street",
    ],
  },

  {
    id: 3,
    category: "Street",
    name: "KTM Duke 125",
    specsTrue: false,

    slug: "ktm-duke-125",
    tour: false,
    rental: true,
    buy: true,
    image: "duke.jpeg",
    shout: "A moto de rua definitiva",
    description:
      "A KTM Duke é conhecida por ser o predador supremo em seu domínio, com o motor 125 mais poderoso do mercado.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },
  {
    id: 4,
    category: "Aventura",
    name: "GAS GAS 700 ES",
    slug: "gasgas-700-es",
    specsTrue: false,

    tour: false,
    rental: true,
    buy: true,
    image: "gasgas-700-es.jpeg",
    shout: "A máquina definitiva de aventura",
    description:
      "Transformando cada estrada e trilha fora de estrada em uma série de playgrounds contínuos, o manejo ágil e a posição de pilotagem inspirada no offroad transmitem confiança e injetam diversão em cada passeio.",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 11500,
    manufacturer: "KTM",
    link: "https://www.ktm.com/en-gb/models/enduro/2-stroke/2024-ktm-300-exc.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },
  {
    id: 5,
    category: "Enduro",
    name: "GAS GAS 300 EC",
    specsTrue: true,
    slug: "gasgas-300-ec",
    tour: true,
    rental: true,
    buy: true,
    image: "gasgas-300-ec.jpeg",
    shout: "A máquina definitiva de enduro duro fora de estrada",
    description:
      "Prefere enduro técnico a desviar de árvores em alta velocidade? Bem, se o que te empolga é o extremo, então a nossa EC 300 é definitivamente para você! Projetada do zero para enfrentar o terreno mais áspero, esta máquina de enduro ultra-moderna é leve, poderosa e faz o trabalho facilmente. Com muito torque em baixa rotação e suspensão WP macia e fácil de ajustar, esses longos e cansativos dias na moto se tornam muito mais agradáveis a bordo da EC 300. Então, para onde você vai levar a sua?",
    weight: 105,
    tank: 9,
    displacement: 293,
    cylinders: 1,
    stroke: 2,
    seatHeight: 963,
    starter: "elétrico",
    cooling: "líquido",
    gears: 6,
    horsepower: 49,
    kw: 37,
    maxSpeed: 130,
    price: 10500,
    manufacturer: "GAS GAS",
    link: "https://www.gasgas.com/en-pt/models/enduro/2-stroke/ec-300-2025.html",
    tags: [
      "durável",
      "ágil",
      "confiável",
      "confortável",
      "leve",
      "versátil",
      "fora de estrada",
      "corrida profissional",
    ],
  },
];
